name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  # todo lo que esté en models/sql_server_dbo/...
  sql_server_dbo:
    +materialized: view
    +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
    +schema: sql_server_dbo

  # y lo mismo para google_sheets
  google_sheets:
    +materialized: view
    +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
    +schema: google_sheets

  # tus marts/core sigue igual
  marts:
    core:
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"
      +schema: core
