name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths:  ["seeds"]         # ← aquí
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  my_new_project:
    zipcode_enriquecido:       # ← coincide con seeds/zipcode_enriquecido.csv
      header: true
      delimiter: ','
      quote: '"'
      trim_quotes: true

models:
  sql_server_dbo:
    +materialized: view
    +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
    +schema: sql_server_dbo

  google_sheets:
    +materialized: view
    +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
    +schema: google_sheets

  marts:
    core:
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"
      +schema: core
