name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +transient: false
  my_new_project:
    staging:
      +materialized: view
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
      google_sheets:
        +schema: google_sheets
      sql_server_dbo:
        +schema: sql_server_dbo

    marts:
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"

      core:
        +schema: core  # ✅ solo para dim_*

      
        
seeds:
  +schema: seed_data
  +database: "{{ env_var('DBT_ENVIRONMENTS') }}_BRONZE_DB"

snapshots:
  +transient: false
  +target_database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
  +target_schema: snapshots

vars:
  surrogate_key_treat_nulls_as_empty_strings: True
