version: 2

models:
  - name: fct_order_items
    description: >
      Tabla de hechos que representa los ítems de cada pedido. 
      Incluye información del producto, cantidad y sincronización.
    columns:
      - name: order_id
        description: ID del pedido relacionado.
        tests:
          - not_null

      - name: product_id
        description: ID del producto relacionado.
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id

      - name: quantity
        description: Cantidad del producto.
        tests: [not_null]

      - name: price
        description: Precio unitario del producto.
        tests: [not_null]

      - name: synced_at
        description: Momento de sincronización de los datos.
        tests:
          - not_null
          - relationships_to_dim_date  # ✅ test a dim_date

    tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - product_id

  - name: fct_orders
    description: >
      Tabla de hechos que representa los pedidos realizados.
    columns:
      - name: order_id
        description: ID único del pedido.
        tests: [not_null, unique]

      - name: user_id
        description: ID del usuario que realizó el pedido.
        tests: [not_null]

      - name: promo_id
        description: ID de la promoción aplicada al pedido (puede estar vacía).

      - name: address_id
        description: ID de la dirección de envío.
        tests: [not_null]

      - name: CREATED_AT
        description: Fecha truncada a día de creación del pedido.
        tests:
          - not_null
          - relationships_to_dim_date  # ✅ test a dim_date

      - name: delivered_at
        description: Fecha truncada a día de entrega (puede ser nula si no ha sido entregado).
        tests:
          - relationships_to_dim_date  # ✅ test a dim_date

      - name: order_cost
        description: Costo total de productos.
        tests: [not_null]

      - name: shipping_cost
        description: Costo del envío.
        tests: [not_null]

      - name: order_total
        description: Total del pedido (productos + envío).
        tests: [not_null]

      - name: synced_at_utc
        description: Fecha original con timestamp de sincronización de Fivetran.
        tests:
          - not_null

      - name: synced_at_date
        description: Fecha truncada a día de sincronización de Fivetran.
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date

      - name: order_status_sk
        description: Clave surrogate del estado del pedido.
        tests:
          - not_null
          - relationships:
              to: ref('dim_order_status')
              field: order_status_sk

